KomodoPlatform/dPoW

.github/workflows/main.yml

sync master

---

README.md

badges creating with https://github.com/google/pybadges by https://github.com/tonymorony/dpow_badges

Added notarizations status badges

---

README.md

temporary install instructions for NN operations

add HUSH3 install instructions

---

iguana/m_notary_KMD

Reverts KomodoPlatform/dPoW#26

Revert "new server ip"

---

iguana/assetchains.old
iguana/launch_assetchains.sh
iguana/listassetchainparams

Assetchains launch script, from komodod repo

Assetchains launch script

---

.github/workflows/main.yml
doc/bible.md

Specifically the notion of "mine blocks" and "network contribution/good"

Hunting clarity

---

iguana/dpow/dpow_rpc.c

j was incremented at the beginning of the loop and in PR 186, I moved it to the end of the loop to be sure to take into account j = 0 but I forgot to take into account two cases with **continue;**
https://github.com/KomodoPlatform/dPoW/pull/186/files
I think that this new change fixes this problem. To be tested, discussed, analysed, code reviewed and merged.

Possible fix to avoid infinite loop (in rare cases) after PR 186

---

iguana/notary.sh

Remove old notary
fix 3P coins

fixed old NN IP and new 3P

---

doc/bible.md

Align dates for snapshots, voting and scoring calcs.
Dates in PR are tentative and subject to change given input from marketing / dev teams

Align dates for snapshots, voting and scoring calcs.

---

doc/bible.md

Previous rules 4 and 11 were pretty much the same. Tweaked rule 4 to include link, removed rule 11

Update bible.md - Merge rule duplication

---

doc/bible.md

Veterans should not be restricted any more than new entrants.

resolve region locking restriction on veteran proposals

---

doc/update038.md

cc: @smk762 
thanks @webworker01

corrects update38 doc

---

doc/update040.md

update 0.4.0 instructions

---

README.md
iguana/assetchains.json
iguana/assetchains.old

aligning with active dpow coins in https://github.com/KomodoPlatform/dPoW/blob/dev/README.md

Update assetchains.json & assetchains.old

---

doc/bible.md

[doc/bible] Fix grammar in Duties-xii

---

doc/bible.md

* LTC -> BTC
* AtomicDEX-API node operating (https://github.com/KomodoPlatform/atomicDEX-API/issues/654)
* Styling/clarifications

s5 bible updates

---

doc/update052.md
doc/update053.md

updates 052 doc with iguana rebuild instruction

---

doc/scoring_epochs.json

ref: https://github.com/KomodoPlatform/dPoW/commit/6eed5fbff0a73d914f11ab4a63694b979a2ab1c7

Scoring timestamps for MIL / CLC / GLEEC-OLD

---

doc/bible.md

ref: https://komodoplatform.com/en/blog/sixth-annual-notary-node-election/

update dates for S6 election

---

doc/bible.md

Tested and notarisation sighted
```
>>>>>>>>>>> VOTE2022 dpow_sendrawtransaction (e761495904465e1949ba2fb53137d05aabf073fbb7b5c56cd0ed19b6ad469b6c)
```
EDIT: hijacked PR to sync dev branch (resolves conflicts)

sync dev branch

---

doc/bible.md

There is some confusion, added this to avoid it being misinterpreted.

add election epoch timestamps

---

iguana/main.c
pnacl_main.h

Simple help text to see CLI parameters available for iguana.

Simple CLI help

---

iguana/m_notary_3rdparty
iguana/m_notary_main
iguana/m_notary_verusholdover

Adds additional seeds for all 3 networks
Removes MIL, CHIPS and VRSC from the 3p network
Adds MIL and CHIPS to "holdover" network

holdover addtions, new seeds
